include: package:flutter_lints/flutter.yaml

linter:

  rules:
    prefer_single_quotes: true
    always_declare_return_types: true
    always_put_required_named_parameters_first: false
    always_use_package_imports: true
    avoid_empty_else: true
    await_only_futures: true