name: gh_repo_search
description: A flutter app for GitHub repo searching
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: any
  flutter_bloc: ^9.1.1
  provider: ^6.1.5
  freezed_annotation: ^3.0.0
  rxdart: ^0.28.0
  dio: ^5.8.0+1
  go_router: ^15.1.2
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  mockito: ^5.4.6
  bloc_test: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
